U413.MvcUI/ViewModels/TerminalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using U413.Domain.Objects;

namespace U413.MvcUI.ViewModels
{
    public class TerminalViewModel
    {
        public string Display { get; set; }
        public string Notifications { get; set; }
        public string Cli { get; set; }
        public string ContextText { get; set; }
        public bool PasswordField { get; set; }
        public string Title { get; set; }
        public string SessionId { get; set; }
    }
}

U413.MvcUI/Controllers/RSSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Xml.Linq;

namespace U413.MvcUI.Controllers
{
    public class RSSController : Controller
    {
        public RedirectResult HuffAndStapes()
        {
            return RedirectPermanent("http://www.CodeTunnel.com/RSS/HuffAndStapes");
        }
    }
}

U413.MvcUI/Controllers/TerminalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using U413.Domain;
using U413.Domain.Objects;
using U413.MvcUI.ViewModels;
using U413.Domain.ExtensionMethods;
using System.Web.Security;
using U413.Domain.Settings;
using System.Text;
using U413.Domain.Enums;
using System.Net;
using System.Configuration;

namespace U413.MvcUI.Controllers
{
    [ValidateInput(false)]
    public class TerminalController : Controller
    {
        private TerminalApi _terminalApi;
        private CommandContext _commandContext;

        public TerminalController(TerminalApi terminalApi)
        {
            _terminalApi = terminalApi;
        }

        public ViewResult Index(string Cli, string Display)
        {
            AppSettings.ConnectionString = ConfigurationManager.ConnectionStrings["EntityContainer"].ConnectionString;

            if (Session["apiSessionId"] == null)
                Session["apiSessionId"] = new WebClient().DownloadString(ConfigurationManager.AppSettings["ApiUrl"] + "GetSessionId");

            ModelState.Clear();
            if (Session["commandContext"] != null)
                _commandContext = (CommandContext)Session["commandContext"];
            _terminalApi.Username = User.Identity.IsAuthenticated ? User.Identity.Name : null;
            _terminalApi.CommandContext = _commandContext;
            _terminalApi.ParseAsHtml = true;
            var commandResult = _terminalApi.ExecuteCommand(Cli);

            if (commandResult.ClearScreen)
                Display = null;

            if (User.Identity.IsAuthenticated)
            {
                if (commandResult.CurrentUser == null)
                    FormsAuthentication.SignOut();
            }
            else
            {
                if (commandResult.CurrentUser != null)
                    FormsAuthentication.SetAuthCookie(commandResult.CurrentUser.Username, false);
            }

            Session["commandContext"] = commandResult.CommandContext;

            var display = new StringBuilder();
            foreach (var displayItem in commandResult.Display)
            {
                display.Append(displayItem.Text);
                display.Append("<br />");
            }

            if (Display != null)
                Display += "<br />";

            var viewModel = new TerminalViewModel
            {
                Cli = commandResult.EditText,
                ContextText = commandResult.CommandContext.Command
                + (commandResult.CommandContext.Text.IsNullOrEmpty() 
                ? null : string.Format(" {0}", _terminalApi.CommandContext.Text)),
                Display = Display + display.ToString(),
                PasswordField = commandResult.PasswordField,
                Notifications = string.Empty,
                Title = commandResult.TerminalTitle,
                SessionId = Session["apiSessionId"].ToString()
            };

            return View(viewModel);
        }
    }
}

U413.MvcUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @if (DateTime.Now.Month == 10)
    {
        <link href="@Url.Content("~/Content/styles/Terminal_Halloween.css")" rel="stylesheet" type="text/css" />
    }
    else if (DateTime.Now.Month == 12)
    {
        <link href="@Url.Content("~/Content/styles/Terminal_xmas.css")" rel="stylesheet" type="text/css" />
    }
    else
    {
        <link href="@Url.Content("~/Content/styles/Terminal.css")" rel="stylesheet" type="text/css" />
    }
    <link href="@Url.Content("~/Content/styles/Prettify.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://www.google.com/jsapi?key=ABQIAAAAwP0Xtu2qzWdkyAHs78XrqBSTibpMIyfoWuh352Yttd2WIWmGsRTB3MI2VDBRax_FPSNz39DY55Xh0g"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/snowfall.min.jquery.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/prettify.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/soundmanager2-nodebug-jsmin.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.scrollTo-min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.coolType_1.2.0.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.u413Client.js")"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-7292713-14']);
        _gaq.push(['_setDomainName', '.u413.com']);
        _gaq.push(['_trackPageview']);

        (function ()
        {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</head>
<body>
    <!--[if lt IE 9]>
        <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative; z-index: 9000;'>
        <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.codetunnel.com/content/images/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
        <div style='width: 780px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
            <div style='width: 75px; float: left;'><img src='http://www.codetunnel.com/content/images/ie6nomore-warning.jpg' alt='Warning!'/></div>
            <div style='width: 400px; float: left; font-family: Arial, sans-serif;'>
            <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated and unsupported browser</div>
            <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a newer web browser.</div>
            </div>
            <div style='width: 75px; float: left;'><a href='http://www.google.com/chrome' target='_blank'><img src='http://www.codetunnel.com/content/images/browser_logos/chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
            <div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='http://www.codetunnel.com/content/images/browser_logos/firefox.jpg' style='border: none;' alt='Get Firefox'/></a></div>
            <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='http://www.codetunnel.com/content/images/browser_logos/safari.jpg' style='border: none;' alt='Get Safari'/></a></div>
            <div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='http://www.codetunnel.com/content/images/browser_logos/ie.jpg' style='border: none;' alt='Get Internet Explorer'/></a></div>
        </div>
        </div>
    <![endif]-->
    @RenderBody()
</body>
</html>

U413.MvcUI/Views/Terminal/Index.cshtml
@model U413.MvcUI.ViewModels.TerminalViewModel
@using U413.Domain.Utilities;
@using System.Configuration;
@{
    ViewBag.Title = Model.Title;
}
<script type="text/javascript">
    var rootPath = '@Url.Content("~")';
    soundManager.url = rootPath + 'Content/SoundManager2/';
    //soundManager.useHTML5Audio = true;
    soundManager.allowScriptAccess = 'always';
    $(function ()
    {
        @if (DateTime.Now.Month == 10)
        {
            <text>
                soundManager.onready(function ()
                {
                    soundManager.createSound({
                        id: 'halloween',
                        url: rootPath + 'Content/sounds/TheDarkeningGround.mp3',
                        autoLoad: true,
                        autoPlay: true,
                        stream: true,
                        volume: 75
                    });
                });
                Setup(rootPath + 'Content/sounds/typewriter.mp3');
                StopButton('halloween');
            </text>
        }
        else if (DateTime.Now.Month == 12)
        {
            <text>
                soundManager.onready(function ()
                {
                    soundManager.createSound({
                        id: 'xmas',
                        url: rootPath + 'Content/sounds/Maenam.mp3',
                        autoLoad: true,
                        autoPlay: true,
                        stream: true,
                        volume: 75
                    });
                });
                Setup(rootPath + 'Content/sounds/techtyping.mp3');
                StopButton('xmas');
                $(document).snowfall({ flakeIndex: 9000, minSize: 1, maxSize: 5, round: true, flakeCount: 100 });
            </text>
        }
        else
        {
            @:Setup(rootPath + 'Content/sounds/techtyping.mp3');
        }
    });

    function StopButton(soundName)
    {
        $('<img src="' + rootPath + 'Content/stop.png" />').css({
            position: 'fixed',
            right: 20,
            top: 20,
            width: '25px',
            cursor: 'pointer',
            zIndex: 9000,
            opacity: '.50'
        }).prependTo('body')
        .click(function (e)
        {
            soundManager.pause(soundName);
            $(this).hide();
            PlayButton(soundName);
        });
    }

    function PlayButton(soundName)
    {
        $('<img src="' + rootPath + 'Content/play.png" />').css({
            position: 'fixed',
            right: 20,
            top: 20,
            width: '25px',
            cursor: 'pointer',
            zIndex: 9000,
            opacity: '.50'
        }).prependTo('body')
        .click(function (e)
        {
            soundManager.resume(soundName);
            $(this).hide();
            StopButton(soundName);
        });
    }

    function Setup(soundFile)
    {
        $(window).resize(function ()
        {
            $('#frame').height($(window).height() - 175);
        }).resize();

        $.coolType.setup(
        {
            soundFile: soundFile,
            playSound: true,
            speed: 25,
            onSoundLoaded: function ()
            {
                $('#commandForm').u413Client(
                {
                    elementToScroll: '#frame > .subFrame',
                    apiUrl: '@ConfigurationManager.AppSettings["ApiUrl"]',
                    sessionId: '@Model.SessionId'
                });
            }
        });
    }
</script>
@if (DateTime.Now.Month == 10)
{
    @:<img class="backgroundImage" src="@Url.Content("~/content/background_halloween.jpg")">
}
else if (DateTime.Now.Month == 12)
{
    @:<img class="backgroundImage" src="@Url.Content("~/content/background_xmas.jpg")">
}
else
{
    @:<img class="backgroundImage" src="@Url.Content("~/content/background.jpg")">
}
<div style="top: 0; left: 0; width: 100%; position: absolute; z-index: 1;">
    <div id="frame">
        <div class="opacityFrame">
        </div>
        <div class="subFrame" style="overflow:auto;">
            @using (Html.BeginForm("Index", "Terminal", FormMethod.Post, new { id = "commandForm" }))
            {
                <div>
                    <div id="terminalDisplay">
                        <noscript>
                            @Html.Raw(Model.Display)
                        </noscript>
                    </div>
                    @Html.HiddenFor(x => x.Display)
                    <div id="notifications">
                        <noscript>
                            @Html.Raw(Model.Notifications)
                        </noscript>
                    </div>
                    @Html.HiddenFor(x => x.Notifications)
                    <div id="loading">
                    </div>
                    <span id="contextDisplay"><span id="context"><noscript>@Model.ContextText</noscript></span>&gt;&nbsp;</span>
                    @if (Model.PasswordField)
                    {
                        @Html.PasswordFor(x => x.Cli, new { autofocus = "autofocus", autocomplete = "off" })
                    }
                    else
                    {
                        @Html.TextBoxFor(x => x.Cli, new { autofocus = "autofocus", autocomplete = "off" })
                    }
                </div>
                <br />
                <br />
            }
        </div>
    </div>
</div>